### ISSUE TITLE
Guide to install

### ISSUE THREAD

**Issue by ericpadilla** [istornz/iPokeGo#2]
Could anyone provide a guide to install this to your ios? thanks!

**Comment by ericpadilla** [comment]
I am using windows, and i found out that xcode is only compatible with mac

**Comment by areteCocoa** [comment]
You need Xcode 8 beta which requires an Apple developer account (free) and a Mac. I do not know of any way to install Xcode projects onto an iPhone via Windows currently.

**Comment by ericpadilla** [comment]
ok, thanks for the reply!

**Comment by SkOODaT** [comment]
its pretty easy 
1. install xcode 8 beta 
2. load the xcode project in xcode
3. choose your own itunes account as a team 
4. plug in your device and at the top select it in the dropdown
5. hit the play button it should compile and transfer over to the device pluged in and open
6. unplug and enjoy the app

* Worth noting that if this is the first app you install under your own itunes account you will need to approve it under setting--general--profiles   click trust

**Comment by ericpadilla** [comment]
i'll try virtual box and see what happens. Thanks!

**Comment by VergaraF** [comment]
Have you guys thought of portraying this to Swift?

**Comment by Spettacolo83** [comment]
Hello there, thank you for your project! What I need to write into the Server textedit? Thank you!

**Comment by mattrat88** [comment]
It won't let me install says I don't have the profile what am I doing wrong

**Comment by swablueme** [comment]
Is there any chance at all that this can be packaged as an IPA or deb? 
I don't have a mac.

**Comment by Dasutin** [comment]
Very unlikely. You gotta sign the ipa with your own developer account.  If you don't have a Mac, you gotta wait until it's in the App Store.  

Anyone who's have thing issues getting this working, Google how to sideload apps for iOS with a free developer account.

**Comment by swablueme** [comment]
@Dasutin Ok, thanks for the reply! I thought it was something like that.

**Comment by tonygils** [comment]
hi,

i got error on the iphone firmware. it say requires ios10.

**Comment by philipp-r** [comment]
The IP address or domain of the server where you run https://github.com/AHAAAAAAA/PokemonGo-Map.

You could use [Heroku](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Heroku-Deployment) or run on your pc and use [forward](https://forwardhq.com).

**Comment by Azzivo** [comment]
"An App ID with Identifier 'com.dimitri-dessus.iPokeGo' is not available. Please enter a different string." Getting this error on my Macbook Pro.

**Comment by philipp-r** [comment]
Change the identifier in Xcode from 'com.dimitri-dessus.iPokeGo' to something like 'com.YOUR_NAME.iPokeGo'. 
Should work then

**Comment by ZihanTang** [comment]
Did you have a version available for Xcode 7.3 or something? it took tons of time to install Xcode 8 beta...

**Comment by mattrat88** [comment]
@philipp-r   
Yea does work tried last night was having same issue said why not let's tester out lol

**Comment by ZihanTang** [comment]
Say I could visit Pokemon map at something@herokuapp.com, then should  server be something@herokuapp.com:5000? 
Anyone knows what the port number is when I use automatically Heroku deployment?

**Comment by philipp-r** [comment]
@ZihanTang when I used the auto deployment to heroku it was something like: https://pokemonmap.herokuapp.com 
Without port!

**Comment by DoDoSt** [comment]
For me it's without port and without https:// .

**Comment by moflowfazzle** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map and https://pokemonmap.herokuapp.com 
is not working for me, i just get a very empty map...
any ideas what server i could use to make it work?

**Comment by philipp-r** [comment]
@moflowfazzle  `https://pokemonmap.herokuapp.com` was just an example.
You need to install [this software](https://github.com/AHAAAAAAA/PokemonGo-Map) on a server. You could use for example [Heroku](https://github.com/AHAAAAAAA/PokemonGo-Map/wiki/Heroku-Deployment) or your own PC.

**Comment by ZihanTang** [comment]
@philipp-r Yeah, I deployed it on Heroku and something.heroku.com could be visited via a browser. However, there is still no pokemon showing up in iPokeGo... When I checked out the log, it shows as bellow.
![screen shot 2016-07-26 at 11 51 12 am](https://cloud.githubusercontent.com/assets/12687471/17145302/a91b1514-5327-11e6-9cf8-b740702c9f67.png)

**Comment by DoDoSt** [comment]
@ZihanTang try the Url without the http://

**Comment by antonkushpil** [comment]
Guys PLEASE add support for XCode 7!!! I use Yosemite, so need to update to ElCap it sooooo long. Or could you please just send me invite to TestFlight anton.kushpil@gmail.com Thanks in advance!!!!

**Comment by ZihanTang** [comment]
Based on commit log, it now support Xcode 7

**Comment by Bizadon** [comment]
Hi guys, I am using vmware with mac, to install the programm, but I faced with the problem that xcode 8 doest install, when I try to expand Xcode_8_beta_3.xip file there goes a window with the error that "The operation couldnt be completed. cpio read error: Undefined error: 0. Does someone know to deal in with it?

**Comment by buckycu** [comment]
Bizadon, what OS X are you using? Xcode 8 is supported on 10.11+. My computer is running on 10.9.5 and I got that error when trying to decompress the file. I wish there were a workaround for Xcode 6.3. I don't want to install El Capitan on my 7-yo computer yet.

**Comment by Bizadon** [comment]
@buckycu I have just 10.11 without anything, this isnt enough?

**Comment by buckycu** [comment]
@Bizadon According to [Wiki](https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_8.x_.28since_Free_On-Device_Development.29), the minimum is 10.11.5. So if your OS is lower than that, try upgrading the OS. Otherwise, I have no idea.

**Comment by Bizadon** [comment]
@buckycu yeah, tried to download before my reply to you and all finished, updated up to 10.11.6, now xip file of xcode is expanding. And what about ios on iphone? Is 9.2 enough or I need to update to the latest version?

**Comment by buckycu** [comment]
@Bizadon They say on the front page that "This app works with all iPhone/iPod Touch and iPad, you only need iOS 8 or more." You should be fine.

**Comment by xXFettiXx** [comment]
please help!
<img width="1440" alt="capture d ecran 2016-08-01 a 01 06 45" src="https://cloud.githubusercontent.com/assets/20721026/17279986/4b229fa2-5784-11e6-836a-849fe3b710a6.png">

**Comment by antonkushpil** [comment]
Change your bundle identifier according to team name

*Anton Kushpil*

*Senior Software Test Automation Engineer*



*Office: *+380 44 390 5457 <+380%2044%20390%205457> *x* 66514   *Email: *
anton. <anton_kushpil@epam.com>kushpil@gmail.com

*Kyiv,* *Ukraine *(GMT+3)   *epam.com <http://www.epam.com>*



CONFIDENTIALITY CAUTION AND DISCLAIMER
This message is intended only for the use of the individual(s) or
entity(ies) to which it is addressed and contains information that is
legally privileged and confidential. If you are not the intended recipient,
or the person responsible for delivering the message to the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of this communication is strictly prohibited. All unintended
recipients are obliged to delete this message and destroy any printed
copies.

**Comment by SnakeIz** [comment]
Anyone idea why I am getting this error when trying to build?

clang error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by SnakeIz** [comment]
still can't figure out how to build the latest with that error
